stages:
  - stage: QA
    displayName: 'Run Playwright Tests for QA Environment'
    jobs:
      - job: RunTestsQA
        displayName: 'Running Playwright Regression Tests'
        steps:
          - script: npm ci
            displayName: 'Install Dependencies'
            workingDirectory: $(Build.SourcesDirectory)

          - script: npx playwright install --with-deps
            displayName: 'Install Playwright'
            workingDirectory: $(Build.SourcesDirectory)

          - script: npm run test:regression:qa
            displayName: 'Run Playwright Regression Tests'
            workingDirectory: $(Build.SourcesDirectory)

          - script: ls -R $(Build.SourcesDirectory)/reports/allure-results
            displayName: 'List Allure Report Folder Contents'
            condition: always()

          - task: PublishTestResults@2
            displayName: 'Publish JUnit Report'
            inputs:
              searchFolder: 'test-results'
              testResultsFormat: 'JUnit'  
              testResultsFiles: '**/test-results.xml' 
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'QA Playwright Regression Test'
            condition: succeededOrFailed()

          - task: PublishPipelineArtifact@1
            displayName: 'Publish HTML Report'
            inputs:
              targetPath: $(Build.SourcesDirectory)/test-results/html/index.html
              artifact: playwright-report
              publishLocation: 'pipeline'
            condition: succeededOrFailed()

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Code Coverage Results'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: $(Build.SourcesDirectory)/coverage/cobertura-coverage.xml
              pathToSources: $(Build.SourcesDirectory)/coverage
            condition: succeededOrFailed()

          - task: PublishAllureReport@1
            displayName: 'Publish Allure Report'
            inputs:
              testResultsDir: '$(Build.SourcesDirectory)/reports/allure-results'
              reportName: 'Allure-Report'
            condition: always()
